### ISSUE TITLE
Add instructions for Mainnet-0

### ISSUE THREAD

**Issue by michaelfig** [Agoric/wallet-app#1]
We'll need to add instructions for Mainnet-0 sometime.  Not urgent yet.

**Comment by michaelfig** [comment]
@samsiegart here's the repo I owe you.  I've verified that it builds and deploys to https://wallet.agoric.app

**Comment by dckc** [comment]
keplr added native support for mainnet0
including mobile: https://github.com/chainapsis/keplr-wallet/commit/d7da63dda2b16103c8288204529d98a6489be7cd
