### ISSUE TITLE
Documentation or examples detailing the use of addOffer

### ISSUE THREAD

**Issue by carlos-kryha** [Agoric/wallet-app#115]
## What is the Problem Being Solved?
In order to have a working dapp on Agoric, wallet-app must be integrated with the dapp's frontend to interact with Agoric contracts. The current examples of this functionality ([dapp-psm](https://github.com/Agoric/dapp-psm), [dapp-inter](https://github.com/Agoric/dapp-inter)) deal only with fungible assets and fail to show how to handle semi-fungible or non-fungible assets. 

After some help from [Office Hours](https://github.com/Agoric/agoric-sdk/discussions/8135), we got a bit further in our `addOffer` integration efforts, but when attempting to use non-fungible assets in the proposal we noticed some issues in the wallet-dapp. For example:

- When signing a tx that results in an error on chain, [WalletBackendAdapter](https://github.com/Agoric/wallet-app/blob/main/wallet/src/util/WalletBackendAdapter.ts#L445) receives an unkown updateRecord (`updateRecord.updated == walletAction`), which halts the entire wallet-app until you clear local storage.
- The following offer 
```js
const offer = {
  id: 1691156828318,
  requestContext: {
      origin: "http://localhost:5173"
  },
  status: "proposed",
  invitationSpec: {
      body: "#{\"source\":\"contract\",\"instance\":\"$0.Alleged: KREAd InstanceHandle\",\"publicInvitationMaker\":\"makeMintCharacterInvitation\"}",
      slots: [
          "board05669"
      ]
  },
  proposalTemplate: {
      want: {
          Asset: {
              amount: {
                  body: "#{\"brand\":\"$0.Alleged: SEVERED: KREAdCHARACTER brand\",\"value\":[{\"name\":\"test\"}]}",
                  slots: [
                      "board05970"
                  ]
              }
          }
      },
      give: {}
  }
}
```
results in this error:
<img src="https://github.com/Agoric/wallet-app/assets/97608823/d302e277-fed1-4a8d-8214-e93d9a47ad9e" width=300  />

I can get around some of the errors by running the wallet-app locally and patching (or ignoring...) them, but I believe implementing an example of addOffer on your end using assets of kind COPY_BAG or COPY_SET would be the most efficient way to find and address these issues, let me know if that would be possible. 

## Description of the Design
n/a
## Security Considerations
n/a
## Test Plan
n/a

**Comment by samsiegart** [comment]
The wallet UI has not been designed to work with, or tested against non-fungible amounts yet, so this requires both a patch as well as documentation after the fact.

@carlos-kryha or @dckc, would you be able to point me to a way to test the wallet UI against a live contract that uses NFTs?

Also RE: `I can get around some of the errors by running the wallet-app locally and patching (or ignoring...) them` - would you be able to point me to a commit or such a patch for reference? I think I know how to fix it regardless, but would be helpful.

**Comment by dckc** [comment]
> @carlos-kryha or @dckc, would you be able to point me to a way to test the wallet UI against a live contract that uses NFTs?

I have some relevant work in progress, but it's not working reliably yet

https://github.com/Agoric/agoric-sdk/tree/7226-sw-nft-issuer/packages/deployment/upgrade-test/upgrade-test-scripts/agoric-upgrade-11/wallet-all-ertp
https://github.com/Agoric/agoric-sdk/blob/master/packages/smart-wallet/test/gameAssetContract.js

2023-08-07 18:40 9ce884092

**Comment by WietzeSlagman** [comment]
https://github.com/Agoric/wallet-app/blob/main/wallet/src/util/WalletBackendAdapter.ts#L445

`      switch (updateRecord.updated) {
        case 'balance': {
          // TODO: Don't assume just one purse per brand.
          // https://github.com/Agoric/agoric-sdk/issues/6126
          const { currentAmount } = updateRecord;
          const purseObj = {
            ...brandToPurse.get(currentAmount.brand),
            currentAmount,
            value: currentAmount.value,
          };
          brandToPurse.set(currentAmount.brand, purseObj);
          updatePurses();
          break;
        }
        case 'offerStatus': {
          const { status } = updateRecord;
          notifierKits.offerUpdates.updater.updateState(status);
          break;
        }
        case 'walletAction': {
          console.log(updateRecord)
          break;
        }
        default: {
          throw Error(`Unknown updateRecord ${updateRecord}`);
        }
      }`
      
    I believe this should fix that wallet error @samsiegart (haven't tested myself but this is what @carlos-kryha  showed me)

**Comment by WietzeSlagman** [comment]
```
      if (updateRecord.updated == 'walletAction') {
        console.warn('Empty update, skipping', updateRecord);
        break;
      }
```

adding this to line 445 of https://github.com/Agoric/wallet-app/blob/main/wallet/src/util/WalletBackendAdapter.ts#L445 omits the error and allows you to continue using the wallet

**Comment by turadg** [comment]
Examples have been provided. New requests please use Discussions or Slack.
