### ISSUE TITLE
Wallet-app fails to display a new incoming offer containing Non-vbank ERTP assets

### ISSUE THREAD

**Issue by WietzeSlagman** [Agoric/wallet-app#117]
## Describe the bug

When the wallet-ui receives an offer through listening to the VStorage, the wallet will on the initial receive error out and not display the offer. However, after a refresh of the app the offer pops up and can be interacted with

The refresh does not work on production app (wallet.agoric.app), however does work on a local version

Referencing this issue here too: #116 as it is also related to offers

## To Reproduce

1. run a local version of wallet-ui
2. go to localhost:3001 or 3000 (depending on your port)
3. receive any non-vbank ERTP NFT offer
4. No offer in wallet pops up
5. console will contain an error
6. refresh tab
7. Offer pops up

## Expected behavior

Expect the offer to be received by the wallet through listening to Vstorage without erroring in the wallet-ui app

## Platform Environment

- MacOS ventura 13.0 with NodeJs v18.16.0
- @agoric/cosmic-swingset@0.41.3-499-g3573f7960

## Additional context

Discussed on a call with @dckc and @turadg going through the entire flow of how to get things to go wrong.

**Comment by turadg** [comment]
We don't expect to continue sending non-vbank ERTP asset offers through the wallet-app bridge so I'm closing this as a known issue. Will reopen if that plan changes.
