### ISSUE TITLE
Error: Unsupported type: '/stride.vesting.StridePeriodicVestingAccount'

### ISSUE THREAD

**Issue by 0xpatrickdev** [Agoric/wallet-app#128]
## Describe the bug

As a wallet-app user, I am unable to transfer assets in from the Stride chain. When I press deposit and confirm amounts I am greeted with `Error: Unsupported type: '/stride.vesting.StridePeriodicVestingAccount'`

## To Reproduce

1. Acquire stATOM on stride by converting staked ATOM (LSM)
2. Go to wallet app and click Deposit next to stATOM
3. Enter an amount, confirm

## Expected behavior

I should be able to transfer my tokens in

## Platform Environment

OS X, Chrome

## Additional context

This error seems to indicate the stargate registry, or more likely amino converters, are not aware of this `accountParser` procedure and it's required for this transaction. It seems a new account type was added for the Cosmos Liquid Staking Module, `StridePeriodicVestingAccount`, that complements `BaseAccount` and `ModuleAccount`.

https://github.com/Stride-Labs/stridejs/blob/42a10e5326fa57368f4a3bd1ce8c38f802245e4e/src/parser.ts#L59-L72

## Screenshots

If applicable, add screenshots to help explain your problem, especially for UI interactions.

**Comment by ivanlei** [comment]
Workaround: use Keplr to IBC onto the agoric chain.
