### ISSUE TITLE
Wallet-UI E2E Testing Completed

### ISSUE THREAD

**Issue by toliaqat** [Agoric/wallet-app#151]
## What is the Problem Being Solved?
All required E2E tests are added for Wallet-UI and running in our CI.
CI will be running for each PR to test if the PR breaks anything in our code against the latest agoric-sdk (local chain).
A periodic CI will also be running against emerynet to test if the master still works with emerynet.

**Comment by rabi-siddique** [comment]
@otoole-brendan
This is the CI video showing the completed test cases for the Wallet UI. Do you think it's ready to be marked as completed?
https://github.com/Agoric/wallet-app/assets/60459172/df6454cc-6be1-40b6-8e33-c9e6ddd9688f

**Comment by otoole-brendan** [comment]
@rabi-siddique I can't see the wallet provisioning step in this video (was expecting to see dialog below) - is this testing opening the wallet UI with an account that already has a smart wallet provisioned?

![Image](https://github.com/Agoric/wallet-app/assets/93355546/e7e0c607-bd6b-4068-9fb4-de71eb5c37da)

**Comment by rabi-siddique** [comment]
> @rabi-siddique I can't see the wallet provisioning step in this video (was expecting to see dialog below) - is this testing opening the wallet UI with an account that already has a smart wallet provisioned?
> 
> ![Image](https://private-user-images.githubusercontent.com/93355546/323663499-e7e0c607-bd6b-4068-9fb4-de71eb5c37da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NTcxNjEsIm5iZiI6MTcxMzQ1Njg2MSwicGF0aCI6Ii85MzM1NTU0Ni8zMjM2NjM0OTktZTdlMGM2MDctYmQ2Yi00MDY4LTlmYjQtZGU3MWViNWMzN2RhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDE2MTQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5NzZiMjFmZWZkYTJhOTA1ODdkYTQ5NjQ4Mjg4MzU3MzA2MjU2ZmU4ZjdiMjZjNTM0ZTBhNTMzYWNmYmMwMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K37PDvLuryKH34FfqsEdhLyQVxrpdVqUJyUrjqFj-mg)

Yes, the wallet has already been provisioned. I need to confirm this with Fraz, but I believe we encountered some obstacles during the provisioning process. Fraz added a test case for this, but we haven't merged it due to its inconsistent behavior. This flakiness occurs when attempting to add BLD to the wallet from the faucet URL.

**Comment by rabi-siddique** [comment]
> @rabi-siddique I can't see the wallet provisioning step in this video (was expecting to see dialog below) - is this testing opening the wallet UI with an account that already has a smart wallet provisioned?
> 
> ![Image](https://private-user-images.githubusercontent.com/93355546/323663499-e7e0c607-bd6b-4068-9fb4-de71eb5c37da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NTcxNjEsIm5iZiI6MTcxMzQ1Njg2MSwicGF0aCI6Ii85MzM1NTU0Ni8zMjM2NjM0OTktZTdlMGM2MDctYmQ2Yi00MDY4LTlmYjQtZGU3MWViNWMzN2RhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDE2MTQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5NzZiMjFmZWZkYTJhOTA1ODdkYTQ5NjQ4Mjg4MzU3MzA2MjU2ZmU4ZjdiMjZjNTM0ZTBhNTMzYWNmYmMwMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K37PDvLuryKH34FfqsEdhLyQVxrpdVqUJyUrjqFj-mg)

Yes, the wallet has already been provisioned. I need to confirm this with Fraz, but I believe we encountered some obstacles during the provisioning process. Fraz added a test case for this, but we haven't merged it due to its inconsistent behavior. This flakiness occurs when attempting to add BLD to the wallet from the faucet URL.

**Comment by rabi-siddique** [comment]
> if it's only testing connecting a users wallet to the dapp where smart wallet already provisioned then this test suffices

@otoole-brendan should we mark wallet-UI test cases as complete?
