### ISSUE TITLE
Read vbank assets from x/bank not wallet.current

### ISSUE THREAD

**Issue by samsiegart** [Agoric/wallet-app#49]
Some (currently all except zoe invitations) purse balances can be queried from the cosmos x/bank module. Since purses are lazily created now, the UI needs to rely on querying x/bank to know the user's true asset balances. The UI should be updated to collate x/bank assets with purse balances.

**Comment by dckc** [comment]
fwiw, [test-watch-balances.js](https://github.com/Agoric/agoric-sdk/blob/dc-wallet-balances-dry/packages/agoric-cli/test/test-watch-balances.js) is WIP to read `x/bank` balances using casting, to get

  - proofs
  - multi-RPC-node fail-over
  - batching

and all those goodies.
